###
POST  http://localhost:1234/signup
Content-Type: application/json

{
    "username":"vetri",
    "password":"1234"
}

###
POST  http://localhost:1234/signin
Content-Type: application/json

{
    "username":"vetri",
    "password":"1234"
}



####
POST https://localhost:1234/chat
Content-Type: application/json

{
     "query": "search operating system"
}